### ISSUE TITLE
Error in launching KOMORAN API server

### ISSUE THREAD

**Issue by eunbee31** [9bow/KOMORANRestAPIServer#2]
안녕하세요,

Komoran 을 테스트 해보고 싶어서 설치하고 있는데요,
다음과 같은 문제에 직면하네요.

저는 https://github.com/9bow/KOMORANRestAPIServer/ 에 나온 대로 
git 클론하고 
gradlew run 을 실행했습니다.

문제점은 무엇인가요?

*************

> Task :run
Loading models...java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
        at kr.co.shineware.nlp.komoran.modeler.model.PosTable.load(PosTable.java:107)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadPosTable(Resources.java:87)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:81)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:26)
        at api.Application.<clinit>(Application.java:8)
java.lang.NullPointerException
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at kr.co.shineware.ds.aho_corasick.model.AhoCorasickNode.load(AhoCorasickNode.java:129)
        at kr.co.shineware.ds.aho_corasick.AhoCorasickDictionary.load(AhoCorasickDictionary.java:33)
        at kr.co.shineware.nlp.komoran.modeler.model.IrregularTrie.load(IrregularTrie.java:79)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadIrregular(Resources.java:114)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:82)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:26)
        at api.Application.<clinit>(Application.java:8)
java.lang.NullPointerException
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at kr.co.shineware.ds.aho_corasick.model.AhoCorasickNode.load(AhoCorasickNode.java:129)
        at kr.co.shineware.ds.aho_corasick.AhoCorasickDictionary.load(AhoCorasickDictionary.java:33)
        at kr.co.shineware.nlp.komoran.modeler.model.Observation.load(Observation.java:84)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadObservation(Resources.java:96)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:83)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:26)
        at api.Application.<clinit>(Application.java:8)
java.lang.NullPointerException
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at kr.co.shineware.nlp.komoran.modeler.model.Transition.load(Transition.java:91)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadTransition(Resources.java:105)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:84)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:26)
        at api.Application.<clinit>(Application.java:8)
java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
        at kr.co.shineware.nlp.komoran.modeler.model.PosTable.load(PosTable.java:107)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadPosTable(Resources.java:87)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:81)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:27)
        at api.Application.<clinit>(Application.java:8)
java.lang.NullPointerException
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at kr.co.shineware.ds.aho_corasick.model.AhoCorasickNode.load(AhoCorasickNode.java:129)
        at kr.co.shineware.ds.aho_corasick.AhoCorasickDictionary.load(AhoCorasickDictionary.java:33)
        at kr.co.shineware.nlp.komoran.modeler.model.IrregularTrie.load(IrregularTrie.java:79)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadIrregular(Resources.java:114)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:82)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:27)
        at api.Application.<clinit>(Application.java:8)
java.lang.NullPointerException
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at kr.co.shineware.ds.aho_corasick.model.AhoCorasickNode.load(AhoCorasickNode.java:129)
        at kr.co.shineware.ds.aho_corasick.AhoCorasickDictionary.load(AhoCorasickDictionary.java:33)
        at kr.co.shineware.nlp.komoran.modeler.model.Observation.load(Observation.java:84)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadObservation(Resources.java:96)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:83)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:27)
        at api.Application.<clinit>(Application.java:8)
java.lang.NullPointerException
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at kr.co.shineware.nlp.komoran.modeler.model.Transition.load(Transition.java:91)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadTransition(Resources.java:105)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:84)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:27)
        at api.Application.<clinit>(Application.java:8)
DONE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
<=========----> 75% EXECUTING [5s]
> :run

**Comment by 9bow** [comment]
안녕하세요, 혹시 실행하셨던 환경(OS, JDK 버전 등)과 전체 Log를 알려주실 수 있으실까요?
동일 환경에서 재현 후 이슈를 해결하도록 하겠습니다. :)

**Comment by eunbee31** [comment]
Windows 에서 실행한 거였으며 jdk1.8.0_201 를 사용했습니다.
전체 Log 라고 하시면 어떤 걸 말씀하시는 건지요? 아래 다시 첨부합니다.
아 제가 무지 초보라 다 이해를 못 하네요 하하

감사합니다.

C:\KOMORANRestAPIServer>gradlew run
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :run
Loading models...java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
        at kr.co.shineware.nlp.komoran.modeler.model.PosTable.load(PosTable.java:107)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadPosTable(Resources.java:87)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:81)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:26)
        at api.Application.<clinit>(Application.java:8)
java.lang.NullPointerException
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at kr.co.shineware.ds.aho_corasick.model.AhoCorasickNode.load(AhoCorasickNode.java:129)
        at kr.co.shineware.ds.aho_corasick.AhoCorasickDictionary.load(AhoCorasickDictionary.java:33)
        at kr.co.shineware.nlp.komoran.modeler.model.IrregularTrie.load(IrregularTrie.java:79)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadIrregular(Resources.java:114)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:82)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:26)
        at api.Application.<clinit>(Application.java:8)
java.lang.NullPointerException
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at kr.co.shineware.ds.aho_corasick.model.AhoCorasickNode.load(AhoCorasickNode.java:129)
        at kr.co.shineware.ds.aho_corasick.AhoCorasickDictionary.load(AhoCorasickDictionary.java:33)
        at kr.co.shineware.nlp.komoran.modeler.model.Observation.load(Observation.java:84)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadObservation(Resources.java:96)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:83)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:26)
        at api.Application.<clinit>(Application.java:8)
java.lang.NullPointerException
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at kr.co.shineware.nlp.komoran.modeler.model.Transition.load(Transition.java:91)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadTransition(Resources.java:105)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:84)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:26)
        at api.Application.<clinit>(Application.java:8)
java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
        at kr.co.shineware.nlp.komoran.modeler.model.PosTable.load(PosTable.java:107)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadPosTable(Resources.java:87)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:81)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:27)
        at api.Application.<clinit>(Application.java:8)
java.lang.NullPointerException
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at kr.co.shineware.ds.aho_corasick.model.AhoCorasickNode.load(AhoCorasickNode.java:129)
        at kr.co.shineware.ds.aho_corasick.AhoCorasickDictionary.load(AhoCorasickDictionary.java:33)
        at kr.co.shineware.nlp.komoran.modeler.model.IrregularTrie.load(IrregularTrie.java:79)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadIrregular(Resources.java:114)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:82)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:27)
        at api.Application.<clinit>(Application.java:8)
DONEjava.lang.NullPointerException

        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at kr.co.shineware.ds.aho_corasick.model.AhoCorasickNode.load(AhoCorasickNode.java:129)
        at kr.co.shineware.ds.aho_corasick.AhoCorasickDictionary.load(AhoCorasickDictionary.java:33)
        at kr.co.shineware.nlp.komoran.modeler.model.Observation.load(Observation.java:84)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadObservation(Resources.java:96)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:83)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:27)
        at api.Application.<clinit>(Application.java:8)
java.lang.NullPointerException
        at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at kr.co.shineware.nlp.komoran.modeler.model.Transition.load(Transition.java:91)
        at kr.co.shineware.nlp.komoran.core.model.Resources.loadTransition(Resources.java:105)
        at kr.co.shineware.nlp.komoran.core.Komoran.<init>(Komoran.java:84)
        at api.KOMORANDemo.<init>(KOMORANDemo.java:27)
        at api.Application.<clinit>(Application.java:8)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
<=========----> 75% EXECUTING [11s]
> :run

이것은 그라들 버전입니다.
------------------------------------------------------------
Gradle 5.2.1
------------------------------------------------------------

Build time:   2019-02-08 19:00:10 UTC
Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Windows 10 10.0 amd64

**Comment by 9bow** [comment]
안녕하세요, 

확인해보니 [KOMORAN 자체에 윈도우에서 모델을 읽지 못하는 문제(#32)](https://github.com/shin285/KOMORAN/issues/32)가 있었습니다. 

현재 버전의 KOMORAN에선 해결된 문제로 다음 중 하나의 방법으로 KOMORAN 버전을 업데이트하실 수 있습니다. 

1. `git clone` 받으신 디렉토리(C:\KOMORANRestAPIServer) 내에서 `git pull` 후 다시 실행하시거나,
2. 또는 직접 [build.gradle 파일에서 KOMORAN 버전을 3.3.4로 수정](https://github.com/9bow/KOMORANRestAPIServer/blob/master/build.gradle#L19)합니다.

위 둘 중 하나의 방법으로 업데이트하신 후, 다시 `gradlew run`을 실행해주세요.

확인하시고 다른 문제가 있으시면 알려주세요. 

감사합니다. :)

**Comment by 9bow** [comment]
@eunbee31 님, 혹시 문제가 해결되셨는지요?

**Comment by eunbee31** [comment]
안녕하십니까,

죄송합니다. 말씀하신 방법 대로 아직 해보지 못했습니다. 
빠르면 이번 주 내에, 늦으면 다음 주에 해볼 수 있을 것 같습니다.

해보고 바로 글 남기겠습니다.
시간 내주셔서 감사합니다. 

은비드림

**Comment by 9bow** [comment]
혹시나 다른 문제를 겪고 계실까 싶어 여쭤봤는데, 재촉한게 되어버려 죄송합니다. ^^;
진행하시면서 이슈가 있으시면 알려주세요!
감사합니다. (_ _)

**Comment by eunbee31** [comment]
안녕하세요,

말씀하신대로 
>1. `git clone` 받으신 디렉토리(C:\KOMORANRestAPIServer) 내에서 `git pull` 후 다시 실행하시거나
를 실행하고서
>다시 `gradlew run`을 실행해주세요.
을 실행했는데요
다음과 같은 오류가 나타납니다:
C:\Users\prometil\eclipse-workspace\KOMORANRestAPIServer>gradlew run
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\prometil\eclipse-workspace\KOMORANRestAPIServer\build.gradle' line: 19

* What went wrong:
Could not compile build file 'C:\Users\prometil\eclipse-workspace\KOMORANRestAPIServer\build.gradle'.
> startup failed:
  build file 'C:\Users\prometil\eclipse-workspace\KOMORANRestAPIServer\build.gradle': 19: unexpected token: << @ line 19, column 1.
     <<<<<<< Updated upstream
     ^

  1 error


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s



또한, 현재 저는 이제 직접 KOMORAN을 clone해서 사용하고 있답니다. 
너무 급한 문제 아님으로 너무 신경 안 쓰셔도 됩니다 허허.

감사합니다.

**Comment by 9bow** [comment]
안녕하세요,

이번에는 gradle 오류로 보여서 다시 테스트해봤는데 뭔가 다른 이슈가 있는 것 같습니다; 우선 KOMORAN을 직접 사용하신다고 하니 이 이슈는 닫고, 추후 유사한 경우가 발생하였을 떄 다시금 살펴보도록 하겠습니다.

더불어 조금 전 새롭게 [KOMORAN 문서 사이트](http://docs.komoran.kr/)와 [Tutorial 저장소](https://github.com/komoran/tutorials)를 업데이트하였으니 확인 부탁드립니다. ^^
(기본적인 환경 설정 방법과 간단한 튜토리얼을 Gradle과 Maven용으로 준비해두었습니다.)

감사합니다. (_ _)

**Comment by eunbee31** [comment]
네, 정말 감사드립니다.
